name: "CodeQL Advanced"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 8 * * 2'

jobs:
  analyze:
    name: Analyze ${{ matrix.language }}
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read  
      actions: read  
      contents: read   
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: python
            build-mode: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

      - name: Create Artifact Directory
        run: mkdir -p artifacts

      - name: Create Dummy Artifact
        run: echo "CodeQL analysis results would go here." > artifacts/codeql-results.txt

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: artifacts/codeql-results.txt  # Ensure this file exists
